courses = [
	{
		'id': 'c1',
		'title': 'Adobe Photoshop Training: From Beginner to Pro',
		'category': 'Design',
		'tutor': {'image': '', 'name': 'Albert Flores'},
		'price': 0,
		'image': '/images/cats.jpg',
		'ratings': 4.5,
		'rating_count': 24167,
		'students': 46995,
		'lectures': 46,
		'level': 'Beginner',
	},
	{
		'id': 'c2',
		'title': 'Cat Behaviour, Psychology and Care Training',
		'category': 'Lifestyle',
		'tutor': {'image': '', 'name': 'Darell Steward'},
		'price': 0,
		'image': '/images/cats.jpg',
		'ratings': 5.0,
		'rating_count': 104716,
		'students': 125725,
		'lectures': 32,
		'level': 'All Levels',
	},
	{
		'id': 'c3',
		'title': 'Ultimate Business Intelligence Analyst A to Z Course 2021',
		'category': 'Business',
		'tutor': {'image': '', 'name': 'Wade Warren'},
		'price': 0,
		'image': '/images/cats.jpg',
		'ratings': 4.8,
		'rating_count': 5803,
		'students': 8023,
		'lectures': 21,
		'level': 'Medium',
	},
	{
		'id': 'c4',
		'title': 'Python Programming Master Class Beginner to Advanced',
		'category': 'Development',
		'tutor': {'image': '', 'name': 'Albert Flores'},
		'price': 0,
		'image': '/images/cats.jpg',
		'ratings': 4.4,
		'rating_count': 54716,
		'students': 84016,
		'lectures': 32,
		'level': 'Medium',
	},
	{
		'id': 'c5',
		'title': 'Stress Management: 40+ easy ways to deal with stress',
		'category': 'Personal Development',
		'tutor': {'image': '', 'name': 'Robert Fox'},
		'price': 0,
		'image': '/images/cats.jpg',
		'ratings': 4.3,
		'rating_count': 6120,
		'students': 8150,
		'lectures': 16,
		'level': 'Medium',
	},
	{
		'id': 'c6',
		'title': 'Social Media Marketing - A to Z Content Marketing Masterclass 2021',
		'category': 'Marketing',
		'tutor': {'image': '', 'name': 'Kristin Watson'},
		'price': 0,
		'image': '/images/cats.jpg',
		'ratings': 4.8,
		'rating_count': 4716,
		'students': 8723,
		'lectures': 46,
		'level': 'All Level',
	},
]
